// Centralized mock data for the ISP OMS system

export const mockUsers = [
  {
    id: "1",
    email: "admin@ispoms.com",
    firstName: "John",
    lastName: "Admin",
    phone: "+27123456789",
    role: {
      id: "1",
      name: "Super Administrator",
      permissions: ["*"],
      createdAt: "2025-01-01T00:00:00Z",
    },
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "2",
    email: "ops@ispoms.com",
    firstName: "Jane",
    lastName: "Operations",
    phone: "+27987654321",
    role: {
      id: "2",
      name: "Operations Manager",
      permissions: ["orders:*", "escalations:*", "customers:read"],
      createdAt: "2025-01-01T00:00:00Z",
    },
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "3",
    email: "sales@ispoms.com",
    firstName: "Mike",
    lastName: "Sales",
    phone: "+27111222333",
    role: {
      id: "3",
      name: "Sales Representative",
      permissions: ["orders:create", "orders:read", "customers:*"],
      createdAt: "2025-01-01T00:00:00Z",
    },
    reportingManagerId: "2",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "4",
    email: "appadmin@ispoms.com",
    firstName: "Lisa",
    lastName: "AppAdmin",
    phone: "+27444555666",
    role: {
      id: "4",
      name: "Application Administrator",
      permissions: ["app_admin:*", "orders:read", "fno:submit_manual"],
      createdAt: "2025-01-01T00:00:00Z",
    },
    reportingManagerId: "2",
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
]

export const mockFNOs = [
  {
    id: "1",
    name: "Openserve",
    code: "OS",
    integrationType: "api" as const,
    apiEndpoint: "https://api.openserve.co.za",
    portalUrl: "https://portal.openserve.co.za",
    coverageAreas: ["Western Cape", "Gauteng", "KwaZulu-Natal"],
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Vumatel",
    code: "VUM",
    integrationType: "manual" as const,
    portalUrl: "https://portal.vumatel.co.za",
    coverageAreas: ["Western Cape", "Gauteng"],
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Frogfoot Networks",
    code: "FF",
    integrationType: "manual" as const,
    portalUrl: "https://portal.frogfoot.com",
    coverageAreas: ["Western Cape", "Eastern Cape"],
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "MetroFibre",
    code: "MF",
    integrationType: "api" as const,
    apiEndpoint: "https://api.metrofibre.co.za",
    portalUrl: "https://portal.metrofibre.co.za",
    coverageAreas: ["Western Cape", "Gauteng", "KwaZulu-Natal"],
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
]

export const mockCustomers = [
  {
    id: "1",
    customerNumber: "CUST-001",
    firstName: "John",
    lastName: "Smith",
    email: "john@example.com",
    phone: "+27123456789",
    address: {
      street: "123 Main Street",
      city: "Cape Town",
      province: "Western Cape",
      postalCode: "8001",
    },
    customerType: "individual" as const,
    isTrial: false,
    createdAt: "2025-01-08T10:30:00Z",
    updatedAt: "2025-01-08T10:30:00Z",
  },
  {
    id: "2",
    customerNumber: "CUST-002",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah@example.com",
    phone: "+27987654321",
    address: {
      street: "456 Business Ave",
      city: "Johannesburg",
      province: "Gauteng",
      postalCode: "2000",
    },
    customerType: "business" as const,
    isTrial: true,
    trialStartDate: "2025-01-05",
    trialEndDate: "2025-02-04",
    createdAt: "2025-01-05T14:20:00Z",
    updatedAt: "2025-01-05T14:20:00Z",
  },
  {
    id: "3",
    customerNumber: "CUST-003",
    firstName: "Mike",
    lastName: "Davis",
    email: "mike@example.com",
    phone: "+27555666777",
    address: {
      street: "789 Oak Road",
      city: "Durban",
      province: "KwaZulu-Natal",
      postalCode: "4000",
    },
    customerType: "individual" as const,
    isTrial: false,
    createdAt: "2025-01-07T09:15:00Z",
    updatedAt: "2025-01-07T09:15:00Z",
  },
]

export const mockOrders = [
  {
    id: "1",
    orderNumber: "ORD-2025-001",
    customer: mockCustomers[0],
    serviceType: "fiber" as const,
    servicePackage: "Premium 100Mbps",
    installationAddress: mockCustomers[0].address,
    fno: mockFNOs[0],
    fnoReference: "OS-REF-12345",
    currentState: "in_progress" as const,
    priority: "high" as const,
    createdBy: mockUsers[1],
    assignedTo: mockUsers[1],
    estimatedCompletion: "2025-01-15T00:00:00Z",
    createdAt: "2025-01-09T10:30:00Z",
    updatedAt: "2025-01-09T14:20:00Z",
  },
  {
    id: "2",
    orderNumber: "ORD-2025-002",
    customer: mockCustomers[1],
    serviceType: "wireless" as const,
    servicePackage: "Standard 50Mbps",
    installationAddress: mockCustomers[1].address,
    fno: mockFNOs[1],
    fnoReference: null,
    currentState: "fno_submitted" as const,
    priority: "normal" as const,
    createdBy: mockUsers[1],
    assignedTo: mockUsers[1],
    estimatedCompletion: "2025-01-12T00:00:00Z",
    createdAt: "2025-01-09T09:15:00Z",
    updatedAt: "2025-01-09T09:15:00Z",
  },
  {
    id: "3",
    orderNumber: "ORD-2025-003",
    customer: mockCustomers[2],
    serviceType: "fiber" as const,
    servicePackage: "Standard 50Mbps",
    installationAddress: mockCustomers[2].address,
    fno: mockFNOs[2],
    fnoReference: "FF-REF-67890",
    currentState: "installation_scheduled" as const,
    priority: "urgent" as const,
    createdBy: mockUsers[2],
    assignedTo: mockUsers[3],
    estimatedCompletion: "2025-01-11T00:00:00Z",
    createdAt: "2025-01-07T11:20:00Z",
    updatedAt: "2025-01-09T09:30:00Z",
  },
  {
    id: "4",
    orderNumber: "ORD-2025-004",
    customer: mockCustomers[0],
    serviceType: "fiber" as const,
    servicePackage: "Business 200Mbps",
    installationAddress: mockCustomers[0].address,
    fno: mockFNOs[2],
    fnoReference: null,
    currentState: "awaiting_fno_submission" as const,
    priority: "normal" as const,
    createdBy: mockUsers[2],
    assignedTo: mockUsers[3],
    estimatedCompletion: "2025-01-14T00:00:00Z",
    createdAt: "2025-01-09T13:45:00Z",
    updatedAt: "2025-01-09T13:45:00Z",
  },
  {
    id: "5",
    orderNumber: "ORD-2025-005",
    customer: mockCustomers[2],
    serviceType: "wireless" as const,
    servicePackage: "Premium 50Mbps",
    installationAddress: mockCustomers[2].address,
    fno: mockFNOs[1],
    fnoReference: "VUM-REF-11111",
    currentState: "fno_submitted" as const,
    priority: "low" as const,
    createdBy: mockUsers[2],
    assignedTo: mockUsers[3],
    estimatedCompletion: "2025-01-16T00:00:00Z",
    createdAt: "2025-01-08T08:30:00Z",
    updatedAt: "2025-01-09T10:20:00Z",
  },
]

// Service packages configuration
export const servicePackages = {
  fiber: [
    { id: "fiber-basic", name: "Basic 25Mbps", price: "R399/month", speed: "25Mbps" },
    { id: "fiber-standard", name: "Standard 50Mbps", price: "R599/month", speed: "50Mbps" },
    { id: "fiber-premium", name: "Premium 100Mbps", price: "R899/month", speed: "100Mbps" },
    { id: "fiber-business", name: "Business 200Mbps", price: "R1299/month", speed: "200Mbps" },
  ],
  wireless: [
    { id: "wireless-basic", name: "Basic 10Mbps", price: "R299/month", speed: "10Mbps" },
    { id: "wireless-standard", name: "Standard 25Mbps", price: "R499/month", speed: "25Mbps" },
    { id: "wireless-premium", name: "Premium 50Mbps", price: "R699/month", speed: "50Mbps" },
  ],
  hybrid: [
    { id: "hybrid-standard", name: "Hybrid 50Mbps", price: "R799/month", speed: "50Mbps" },
    { id: "hybrid-premium", name: "Hybrid 100Mbps", price: "R1099/month", speed: "100Mbps" },
  ],
}

// System configuration
export const systemConfig = {
  escalation: {
    defaultSlaHours: 24,
    reportingManagerEscalationHours: 4,
    processOwnerEscalationHours: 8,
  },
  trial: {
    defaultDurationDays: 30,
    reminderDays: [7, 14, 21, 28],
  },
  onboarding: {
    defaultSteps: ["welcome", "service_setup", "equipment_delivery", "installation", "activation", "follow_up"],
  },
}

export const mockEscalations = [
  {
    id: "1",
    order: mockOrders[0],
    escalationLevel: 1,
    escalatedFrom: mockUsers[2], // Sales Rep
    escalatedTo: mockUsers[1], // Operations Manager
    escalationReason: "Order has been stuck in FNO submission for over 48 hours without response",
    status: "open" as const,
    createdAt: "2025-01-09T08:30:00Z",
  },
  {
    id: "2",
    order: mockOrders[1],
    escalationLevel: 2,
    escalatedFrom: mockUsers[3], // App Admin
    escalatedTo: mockUsers[0], // Super Admin
    escalationReason: "Customer complaint about delayed installation - requires management intervention",
    status: "in_progress" as const,
    createdAt: "2025-01-08T14:20:00Z",
  },
  {
    id: "3",
    order: null,
    taskId: "task-123",
    escalationLevel: 1,
    escalatedFrom: mockUsers[3], // App Admin
    escalatedTo: mockUsers[1], // Operations Manager
    escalationReason: "Manual FNO application has been pending for 6 hours - exceeds SLA",
    status: "resolved" as const,
    resolvedAt: "2025-01-09T16:45:00Z",
    resolutionNotes: "Contacted FNO directly and expedited the application process. Application now approved.",
    createdAt: "2025-01-09T10:15:00Z",
  },
  {
    id: "4",
    order: mockOrders[3],
    escalationLevel: 3,
    escalatedFrom: mockUsers[1], // Operations Manager
    escalatedTo: mockUsers[0], // Super Admin
    escalationReason: "Critical customer - VIP service level - installation team no-show twice",
    status: "open" as const,
    createdAt: "2025-01-09T07:00:00Z",
  },
  {
    id: "5",
    order: null,
    taskId: "onboarding-456",
    escalationLevel: 1,
    escalatedFrom: mockUsers[2], // Sales Rep
    escalatedTo: mockUsers[1], // Operations Manager
    escalationReason: "Trial customer conversion deadline approaching - customer not responding to calls",
    status: "in_progress" as const,
    createdAt: "2025-01-08T16:30:00Z",
  },
]

export const mockApplicationInbox = [
  {
    id: "1",
    order: mockOrders[1],
    fno: mockFNOs[1],
    assignedTo: mockUsers[3],
    priority: "high" as const,
    status: "pending" as const,
    dueDate: "2025-01-10T12:00:00Z",
    createdAt: "2025-01-09T09:15:00Z",
    agingHours: 25,
  },
  {
    id: "2",
    order: mockOrders[4],
    fno: mockFNOs[2],
    assignedTo: null,
    priority: "normal" as const,
    status: "pending" as const,
    dueDate: "2025-01-10T17:45:00Z",
    createdAt: "2025-01-09T13:45:00Z",
    agingHours: 4,
  },
  {
    id: "3",
    order: mockOrders[2],
    fno: mockFNOs[1],
    assignedTo: mockUsers[3],
    priority: "low" as const,
    status: "completed" as const,
    completedAt: "2025-01-09T10:20:00Z",
    notes: "Successfully submitted to Vumatel portal. Reference number: VUM-REF-11111",
    createdAt: "2025-01-08T08:30:00Z",
    agingHours: 0,
  },
]

export const mockOnboarding = [
  {
    id: "1",
    customer: mockCustomers[1], // Trial customer
    order: mockOrders[1],
    onboardingType: "trial" as const,
    currentStep: "service_setup",
    completionPercentage: 40,
    assignedTo: mockUsers[2],
    startedAt: "2025-01-05T14:20:00Z",
    steps: [
      {
        id: "welcome",
        name: "Welcome & Account Setup",
        description: "Initial welcome and account configuration",
        status: "completed" as const,
        completedAt: "2025-01-05T15:00:00Z",
        completedBy: mockUsers[2],
      },
      {
        id: "service_setup",
        name: "Service Configuration",
        description: "Configure service parameters and preferences",
        status: "in_progress" as const,
      },
      {
        id: "equipment_delivery",
        name: "Equipment Delivery",
        description: "Schedule and track equipment delivery",
        status: "pending" as const,
      },
      {
        id: "installation",
        name: "Installation Appointment",
        description: "Schedule and complete service installation",
        status: "pending" as const,
      },
      {
        id: "activation",
        name: "Service Activation",
        description: "Activate service and perform testing",
        status: "pending" as const,
      },
      {
        id: "follow_up",
        name: "Follow-up & Support",
        description: "Post-activation follow-up and support setup",
        status: "pending" as const,
      },
    ],
  },
  {
    id: "2",
    customer: mockCustomers[0], // Regular customer
    order: mockOrders[0],
    onboardingType: "new_customer" as const,
    currentStep: "installation",
    completionPercentage: 75,
    assignedTo: mockUsers[3],
    startedAt: "2025-01-09T10:30:00Z",
    steps: [
      {
        id: "welcome",
        name: "Welcome & Account Setup",
        description: "Initial welcome and account configuration",
        status: "completed" as const,
        completedAt: "2025-01-09T11:00:00Z",
        completedBy: mockUsers[3],
      },
      {
        id: "service_setup",
        name: "Service Configuration",
        description: "Configure service parameters and preferences",
        status: "completed" as const,
        completedAt: "2025-01-09T12:30:00Z",
        completedBy: mockUsers[3],
      },
      {
        id: "equipment_delivery",
        name: "Equipment Delivery",
        description: "Schedule and track equipment delivery",
        status: "completed" as const,
        completedAt: "2025-01-09T14:00:00Z",
        completedBy: mockUsers[3],
      },
      {
        id: "installation",
        name: "Installation Appointment",
        description: "Schedule and complete service installation",
        status: "in_progress" as const,
      },
      {
        id: "activation",
        name: "Service Activation",
        description: "Activate service and perform testing",
        status: "pending" as const,
      },
      {
        id: "follow_up",
        name: "Follow-up & Support",
        description: "Post-activation follow-up and support setup",
        status: "pending" as const,
      },
    ],
  },
]
